# Generated by Django 3.2.5 on 2023-07-06 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Arrival_City', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=50)),
                ('cust_phno', models.BigIntegerField()),
                ('cust_email', models.CharField(max_length=50)),
                ('cust_pswd', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DestinationCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Destination_City', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FlightName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FlightDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FlightNumber', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('ArrivalTime', models.TimeField()),
                ('ArrivalCity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlightApp.arrivalcity')),
                ('DestinationCity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlightApp.destinationcity')),
                ('FlightName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlightApp.flight')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationDetials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phno', models.BigIntegerField()),
                ('age', models.IntegerField()),
                ('booking_status', models.BooleanField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlightApp.customer')),
                ('fight_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlightApp.flightdetails')),
            ],
        ),
    ]
