# Generated by Django 3.2.5 on 2023-07-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightdetails',
            name='Cost',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
